const profiles = [
  {
    ProDpImgsrc:'images/pimg2.jpeg',
    ProName: '#Aalim(you)',
    ProNameBelow: 'Message yourself',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: '<i class="fa-solid fa-lock"></i> Message to yourself are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Select to learn more.',
    DissapearMess: "You use a default timer for disappearing messages in new chats. All new messages will disappear from this chat 24 hours after they're sent, except when kept.",
    DissapearTurnedOff: '<i class="fa-regular fa-clock"></i> Disappearing messages were turned off.',
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg1.jpeg',
    ProName: 'Bsc Besties group',
    ProNameBelow: 'Select for group info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: '~Kaverihirgappa created group "BSc Besties',
    DissapearMess: "You were added",
    DissapearTurnedOff: '<i class="fa-regular fa-clock"></i> Disappearing messages were turned off.',
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg3.jpeg',
    ProName: 'GFGCMX BSc 3rd sem CS',
    ProNameBelow: 'Select for group info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: '+91 9845478101 created group "GFGCMX BSc 3rd sem Cs"',
    DissapearMess: "You were added",
    DissapearTurnedOff: '<i class="fa-regular fa-clock"></i> Disappearing messages were turned off.',
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg4.jpeg',
    ProName: 'Asif Friend',
    ProNameBelow: 'Select for contact info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: '<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.',
    DissapearMess: "You were added",
    DissapearTurnedOff: '<i class="fa-regular fa-clock"></i> Disappearing messages were turned off.',
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg5.jpeg',
    ProName: 'Bsc 3rd sem math...',
    ProNameBelow: 'Select for group info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: '~Bhoomi Darling created group "BSc 2nd sem mathematics group"',
    DissapearMess: "You were added",
    DissapearTurnedOff: '<i class="fa-regular fa-clock"></i> Disappearing messages were turned off.',
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg6.png',
    ProName: 'Sonu',
    ProNameBelow: 'Select for contact info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: `<i class="fa-regular fa-clock"></i> You use a default times for disappearing messages in new chats. New messages will disappear from this chat 24 hours after they're sent, except when kept. Tap to set your own default timer`,
    DissapearMess: "You were added",
    DissapearTurnedOff: '<i class="fa-regular fa-clock"></i> Disappearing messages were turned off.',
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg7.jpeg',
    ProName: 'Darshan Bhai',
    ProNameBelow: 'Select for contact info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: `<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.`,
    DissapearMess: "You were added",
    DissapearTurnedOff: '<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.',
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg8.jpeg',
    ProName: 'Bsc Friends Forever',
    ProNameBelow: 'Select for group info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: `~Vikram M Chavan created group "Bsc Friends Forever"`,
    DissapearMess: "You were added",
    DissapearTurnedOff: '<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.',
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg9.jpeg',
    ProName: 'Balavanta',
    ProNameBelow: 'Select for group info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: `<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.`,
    DissapearMess: "You were added",
    DissapearTurnedOff: `<i class="fa-solid fa-lock"></i> You use a default times for disappearing messages in new chats. New messages will disappear from this chat 24 hours after they're sent, except when kept. Tap to set your own default timer`,
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg10.jpeg',
    ProName: 'Ayyan',
    ProNameBelow: 'Select for group info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: `<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.`,
    DissapearMess: "You were added",
    DissapearTurnedOff: `<i class="fa-solid fa-lock"></i> You use a default times for disappearing messages in new chats. New messages will disappear from this chat 24 hours after they're sent, except when kept. Tap to set your own default timer`,
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg11.jpeg',
    ProName: 'Vishwanath88malikeri',
    ProNameBelow: 'Select for contact info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: `<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.`,
    DissapearMess: "You were added",
    DissapearTurnedOff: `<i class="fa-solid fa-lock"></i> You use a default times for disappearing messages in new chats. New messages will disappear from this chat 24 hours after they're sent, except when kept. Tap to set your own default timer`,
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg12.jpeg',
    ProName: 'Come to allha',
    ProNameBelow: 'Select for group info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: `<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.`,
    DissapearMess: "You were added",
    DissapearTurnedOff: `<i class="fa-solid fa-lock"></i> You use a default times for disappearing messages in new chats. New messages will disappear from this chat 24 hours after they're sent, except when kept. Tap to set your own default timer`,
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg13.jpeg',
    ProName: 'Beeresh',
    ProNameBelow: 'Select for group info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: `<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.`,
    DissapearMess: "You were added",
    DissapearTurnedOff: `<i class="fa-solid fa-lock"></i> You use a default times for disappearing messages in new chats. New messages will disappear from this chat 24 hours after they're sent, except when kept. Tap to set your own default timer`,
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg14.jpeg',
    ProName: 'Harshit',
    ProNameBelow: 'Select for contact info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: `<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.`,
    DissapearMess: "You were added",
    DissapearTurnedOff: `<i class="fa-solid fa-lock"></i> You use a default times for disappearing messages in new chats. New messages will disappear from this chat 24 hours after they're sent, except when kept. Tap to set your own default timer`,
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg15.jpeg',
    ProName: 'Bsc Besties ',
    ProNameBelow: 'Select for group info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: `<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.`,
    DissapearMess: "You were added",
    DissapearTurnedOff: `<i class="fa-solid fa-lock"></i> You use a default times for disappearing messages in new chats. New messages will disappear from this chat 24 hours after they're sent, except when kept. Tap to set your own default timer`,
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg16.jpeg',
    ProName: 'Hanamanthpoojari88',
    ProNameBelow: 'Select for contact info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: `<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.`,
    DissapearMess: "You were added",
    DissapearTurnedOff: `<i class="fa-solid fa-lock"></i> You use a default times for disappearing messages in new chats. New messages will disappear from this chat 24 hours after they're sent, except when kept. Tap to set your own default timer`,
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg17.jpeg',
    ProName: 'Bhagyalata',
    ProNameBelow: 'Select for contact info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: `<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.`,
    DissapearMess: "You were added",
    DissapearTurnedOff: `<i class="fa-solid fa-lock"></i> You use a default times for disappearing messages in new chats. New messages will disappear from this chat 24 hours after they're sent, except when kept. Tap to set your own default timer`,
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg18.png',
    ProName: 'Ismail Shaikh',
    ProNameBelow: 'Select for contact info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: `<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.`,
    DissapearMess: "You were added",
    DissapearTurnedOff: `<i class="fa-solid fa-lock"></i> You use a default times for disappearing messages in new chats. New messages will disappear from this chat 24 hours after they're sent, except when kept. Tap to set your own default timer`,
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg19.jpeg',
    ProName: 'Simple men',
    ProNameBelow: 'Select for contact info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: `<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.`,
    DissapearMess: "You were added",
    DissapearTurnedOff: `<i class="fa-solid fa-lock"></i> You use a default times for disappearing messages in new chats. New messages will disappear from this chat 24 hours after they're sent, except when kept. Tap to set your own default timer`,
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg20.jpeg',
    ProName: 'Gpoojari599',
    ProNameBelow: 'Select for contact info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: `<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.`,
    DissapearMess: "You were added",
    DissapearTurnedOff: `<i class="fa-solid fa-lock"></i> You use a default times for disappearing messages in new chats. New messages will disappear from this chat 24 hours after they're sent, except when kept. Tap to set your own default timer`,
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg21.jpeg',
    ProName: 'Pruthvi',
    ProNameBelow: 'Select for contact info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: `<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.`,
    DissapearMess: "You were added",
    DissapearTurnedOff: `<i class="fa-solid fa-lock"></i> You use a default times for disappearing messages in new chats. New messages will disappear from this chat 24 hours after they're sent, except when kept. Tap to set your own default timer`,
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
  {
    ProDpImgsrc:'images/pimg22.jpeg',
    ProName: 'Fazal',
    ProNameBelow: 'Select for contact info',
    ProMagnifyingIcon:'<i class="fa-solid fa-magnifying-glass"></i>',
    ProBodyDate: '12/26/2023',
    EndToEndMess: `<i class="fa-solid fa-lock"></i> Messages and calls are end-to-end encrypted. No one outside of this chat, not even Whatsapp, can read or listen to them. Tap to learn more.`,
    DissapearMess: "You were added",
    DissapearTurnedOff: `<i class="fa-solid fa-lock"></i> You use a default times for disappearing messages in new chats. New messages will disappear from this chat 24 hours after they're sent, except when kept. Tap to set your own default timer`,
    EncryptP1: 'encryptMessageP1',
    EncryptP2: 'encryptMessageP2',
    EncryptP3: 'encryptMessageP3',
    EncryptP4: 'encryptMessageP4',
    EncryptP5: 'encryptMessageP5',
    EncryptP6: 'encryptMessageP6'
  },
];